# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/scott/Python/CompilerDeck/resources/widget/DeckCompileWidget/DeckCompileWidget.ui'
#
# Created: Sat May  3 00:00:25 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class PySideUiFileSetup(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 504)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(640, 480))
        Form.horizontalLayout_5 = QtGui.QHBoxLayout(Form)
        Form.horizontalLayout_5.setObjectName("horizontalLayout_5")
        Form.mainTab = QtGui.QTabWidget(Form)
        Form.mainTab.setObjectName("mainTab")
        Form.settingsTabPage = QtGui.QWidget()
        Form.settingsTabPage.setObjectName("settingsTabPage")
        Form.verticalLayout_7 = QtGui.QVBoxLayout(Form.settingsTabPage)
        Form.verticalLayout_7.setObjectName("verticalLayout_7")
        Form.widget_4 = QtGui.QWidget(Form.settingsTabPage)
        Form.widget_4.setObjectName("widget_4")
        Form.horizontalLayout_2 = QtGui.QHBoxLayout(Form.widget_4)
        Form.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_2.setObjectName("horizontalLayout_2")
        Form.groupBox_3 = QtGui.QGroupBox(Form.widget_4)
        Form.groupBox_3.setObjectName("groupBox_3")
        Form.verticalLayout_6 = QtGui.QVBoxLayout(Form.groupBox_3)
        Form.verticalLayout_6.setObjectName("verticalLayout_6")
        Form.compileModeComboBox = QtGui.QComboBox(Form.groupBox_3)
        Form.compileModeComboBox.setObjectName("compileModeComboBox")
        Form.verticalLayout_6.addWidget(Form.compileModeComboBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        Form.verticalLayout_6.addItem(spacerItem)
        Form.liveCheck = QtGui.QCheckBox(Form.groupBox_3)
        Form.liveCheck.setObjectName("liveCheck")
        Form.verticalLayout_6.addWidget(Form.liveCheck)
        Form.telemetryCheck = QtGui.QCheckBox(Form.groupBox_3)
        Form.telemetryCheck.setObjectName("telemetryCheck")
        Form.verticalLayout_6.addWidget(Form.telemetryCheck)
        Form.horizontalLayout_2.addWidget(Form.groupBox_3)
        Form.platformBox = QtGui.QGroupBox(Form.widget_4)
        Form.platformBox.setObjectName("platformBox")
        Form.verticalLayout_4 = QtGui.QVBoxLayout(Form.platformBox)
        Form.verticalLayout_4.setObjectName("verticalLayout_4")
        Form.webPlatformCheck = QtGui.QCheckBox(Form.platformBox)
        Form.webPlatformCheck.setObjectName("webPlatformCheck")
        Form.verticalLayout_4.addWidget(Form.webPlatformCheck)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        Form.verticalLayout_4.addItem(spacerItem1)
        Form.horizontalLayout_2.addWidget(Form.platformBox)
        Form.groupBox = QtGui.QGroupBox(Form.widget_4)
        Form.groupBox.setObjectName("groupBox")
        Form.verticalLayout_13 = QtGui.QVBoxLayout(Form.groupBox)
        Form.verticalLayout_13.setObjectName("verticalLayout_13")
        Form.iosPlatformCheck = QtGui.QCheckBox(Form.groupBox)
        Form.iosPlatformCheck.setObjectName("iosPlatformCheck")
        Form.verticalLayout_13.addWidget(Form.iosPlatformCheck)
        Form.widget_34 = QtGui.QWidget(Form.groupBox)
        Form.widget_34.setObjectName("widget_34")
        Form.verticalLayout_18 = QtGui.QVBoxLayout(Form.widget_34)
        Form.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_18.setObjectName("verticalLayout_18")
        Form.iosInterpCheck = QtGui.QCheckBox(Form.widget_34)
        Form.iosInterpCheck.setObjectName("iosInterpCheck")
        Form.verticalLayout_18.addWidget(Form.iosInterpCheck)
        Form.simulatorCheck = QtGui.QCheckBox(Form.widget_34)
        Form.simulatorCheck.setObjectName("simulatorCheck")
        Form.verticalLayout_18.addWidget(Form.simulatorCheck)
        Form.verticalLayout_13.addWidget(Form.widget_34)
        Form.androidPlatformCheck = QtGui.QCheckBox(Form.groupBox)
        Form.androidPlatformCheck.setObjectName("androidPlatformCheck")
        Form.verticalLayout_13.addWidget(Form.androidPlatformCheck)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        Form.verticalLayout_13.addItem(spacerItem2)
        spacerItem3 = QtGui.QSpacerItem(20, 78, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        Form.verticalLayout_13.addItem(spacerItem3)
        Form.horizontalLayout_2.addWidget(Form.groupBox)
        Form.groupBox_2 = QtGui.QGroupBox(Form.widget_4)
        Form.groupBox_2.setObjectName("groupBox_2")
        Form.verticalLayout_19 = QtGui.QVBoxLayout(Form.groupBox_2)
        Form.verticalLayout_19.setObjectName("verticalLayout_19")
        Form.airPlatformCheck = QtGui.QCheckBox(Form.groupBox_2)
        Form.airPlatformCheck.setObjectName("airPlatformCheck")
        Form.verticalLayout_19.addWidget(Form.airPlatformCheck)
        Form.nativePlatformCheck = QtGui.QCheckBox(Form.groupBox_2)
        Form.nativePlatformCheck.setObjectName("nativePlatformCheck")
        Form.verticalLayout_19.addWidget(Form.nativePlatformCheck)
        Form.widget_35 = QtGui.QWidget(Form.groupBox_2)
        Form.widget_35.setObjectName("widget_35")
        Form.verticalLayout_20 = QtGui.QVBoxLayout(Form.widget_35)
        Form.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_20.setObjectName("verticalLayout_20")
        Form.nativeCaptiveChk = QtGui.QCheckBox(Form.widget_35)
        Form.nativeCaptiveChk.setObjectName("nativeCaptiveChk")
        Form.verticalLayout_20.addWidget(Form.nativeCaptiveChk)
        Form.verticalLayout_19.addWidget(Form.widget_35)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        Form.verticalLayout_19.addItem(spacerItem4)
        Form.horizontalLayout_2.addWidget(Form.groupBox_2)
        spacerItem5 = QtGui.QSpacerItem(666, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout_2.addItem(spacerItem5)
        Form.verticalLayout_7.addWidget(Form.widget_4)
        Form.widget_2 = QtGui.QWidget(Form.settingsTabPage)
        Form.widget_2.setObjectName("widget_2")
        Form.horizontalLayout = QtGui.QHBoxLayout(Form.widget_2)
        Form.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout.setObjectName("horizontalLayout")
        Form.widget_5 = QtGui.QWidget(Form.widget_2)
        Form.widget_5.setObjectName("widget_5")
        Form.formLayout = QtGui.QFormLayout(Form.widget_5)
        Form.formLayout.setContentsMargins(0, 0, 0, 0)
        Form.formLayout.setObjectName("formLayout")
        Form.label_3 = QtGui.QLabel(Form.widget_5)
        Form.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.label_3.setObjectName("label_3")
        Form.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, Form.label_3)
        Form.flashPlayerComboBox = QtGui.QComboBox(Form.widget_5)
        Form.flashPlayerComboBox.setObjectName("flashPlayerComboBox")
        Form.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, Form.flashPlayerComboBox)
        Form.label_4 = QtGui.QLabel(Form.widget_5)
        Form.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.label_4.setObjectName("label_4")
        Form.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, Form.label_4)
        Form.airSDKComboBox = QtGui.QComboBox(Form.widget_5)
        Form.airSDKComboBox.setObjectName("airSDKComboBox")
        Form.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, Form.airSDKComboBox)
        Form.horizontalLayout.addWidget(Form.widget_5)
        spacerItem6 = QtGui.QSpacerItem(469, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout.addItem(spacerItem6)
        Form.widget = QtGui.QWidget(Form.widget_2)
        Form.widget.setObjectName("widget")
        Form.verticalLayout_5 = QtGui.QVBoxLayout(Form.widget)
        Form.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_5.setObjectName("verticalLayout_5")
        Form.label_5 = QtGui.QLabel(Form.widget)
        Form.label_5.setObjectName("label_5")
        Form.verticalLayout_5.addWidget(Form.label_5)
        Form.remoteDebugComboBox = QtGui.QComboBox(Form.widget)
        Form.remoteDebugComboBox.setObjectName("remoteDebugComboBox")
        Form.verticalLayout_5.addWidget(Form.remoteDebugComboBox)
        Form.horizontalLayout.addWidget(Form.widget)
        Form.verticalLayout_7.addWidget(Form.widget_2)
        Form.widget_7 = QtGui.QWidget(Form.settingsTabPage)
        Form.widget_7.setObjectName("widget_7")
        Form.horizontalLayout_4 = QtGui.QHBoxLayout(Form.widget_7)
        Form.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_4.setObjectName("horizontalLayout_4")
        Form.verticalLayout_7.addWidget(Form.widget_7)
        spacerItem7 = QtGui.QSpacerItem(20, 140, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        Form.verticalLayout_7.addItem(spacerItem7)
        Form.widget_6 = QtGui.QWidget(Form.settingsTabPage)
        Form.widget_6.setObjectName("widget_6")
        Form.horizontalLayout_3 = QtGui.QHBoxLayout(Form.widget_6)
        Form.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_3.setObjectName("horizontalLayout_3")
        Form.widget_33 = QtGui.QWidget(Form.widget_6)
        Form.widget_33.setObjectName("widget_33")
        Form.verticalLayout_16 = QtGui.QVBoxLayout(Form.widget_33)
        Form.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_16.setObjectName("verticalLayout_16")
        Form.compileBtn = QtGui.QPushButton(Form.widget_33)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.compileBtn.setFont(font)
        Form.compileBtn.setObjectName("compileBtn")
        Form.verticalLayout_16.addWidget(Form.compileBtn)
        Form.compileDebugBtn = QtGui.QPushButton(Form.widget_33)
        font = QtGui.QFont()
        font.setPointSize(14)
        Form.compileDebugBtn.setFont(font)
        Form.compileDebugBtn.setObjectName("compileDebugBtn")
        Form.verticalLayout_16.addWidget(Form.compileDebugBtn)
        Form.horizontalLayout_3.addWidget(Form.widget_33)
        spacerItem8 = QtGui.QSpacerItem(852, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout_3.addItem(spacerItem8)
        Form.widget_32 = QtGui.QWidget(Form.widget_6)
        Form.widget_32.setObjectName("widget_32")
        Form.verticalLayout_17 = QtGui.QVBoxLayout(Form.widget_32)
        Form.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_17.setObjectName("verticalLayout_17")
        Form.compileBeforePackageChk = QtGui.QCheckBox(Form.widget_32)
        Form.compileBeforePackageChk.setObjectName("compileBeforePackageChk")
        Form.verticalLayout_17.addWidget(Form.compileBeforePackageChk)
        Form.packagePauseChk = QtGui.QCheckBox(Form.widget_32)
        Form.packagePauseChk.setObjectName("packagePauseChk")
        Form.verticalLayout_17.addWidget(Form.packagePauseChk)
        Form.expandPackageChk = QtGui.QCheckBox(Form.widget_32)
        Form.expandPackageChk.setObjectName("expandPackageChk")
        Form.verticalLayout_17.addWidget(Form.expandPackageChk)
        Form.packageBtn = QtGui.QPushButton(Form.widget_32)
        font = QtGui.QFont()
        font.setPointSize(14)
        Form.packageBtn.setFont(font)
        Form.packageBtn.setObjectName("packageBtn")
        Form.verticalLayout_17.addWidget(Form.packageBtn)
        Form.horizontalLayout_3.addWidget(Form.widget_32)
        Form.verticalLayout_7.addWidget(Form.widget_6)
        Form.mainTab.addTab(Form.settingsTabPage, "")
        Form.utilsTabPage = QtGui.QWidget()
        Form.utilsTabPage.setObjectName("utilsTabPage")
        Form.verticalLayout_15 = QtGui.QVBoxLayout(Form.utilsTabPage)
        Form.verticalLayout_15.setObjectName("verticalLayout_15")
        Form.label_8 = QtGui.QLabel(Form.utilsTabPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        Form.label_8.setFont(font)
        Form.label_8.setObjectName("label_8")
        Form.verticalLayout_15.addWidget(Form.label_8)
        Form.label_9 = QtGui.QLabel(Form.utilsTabPage)
        Form.label_9.setObjectName("label_9")
        Form.verticalLayout_15.addWidget(Form.label_9)
        Form.widget_31 = QtGui.QWidget(Form.utilsTabPage)
        Form.widget_31.setObjectName("widget_31")
        Form.horizontalLayout_20 = QtGui.QHBoxLayout(Form.widget_31)
        Form.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_20.setObjectName("horizontalLayout_20")
        Form.widget_28 = QtGui.QWidget(Form.widget_31)
        Form.widget_28.setObjectName("widget_28")
        Form.gridLayout_3 = QtGui.QGridLayout(Form.widget_28)
        Form.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        Form.gridLayout_3.setObjectName("gridLayout_3")
        Form.runDebugBtn = QtGui.QPushButton(Form.widget_28)
        Form.runDebugBtn.setObjectName("runDebugBtn")
        Form.gridLayout_3.addWidget(Form.runDebugBtn, 0, 0, 1, 1)
        Form.horizontalLayout_20.addWidget(Form.widget_28)
        spacerItem9 = QtGui.QSpacerItem(413, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout_20.addItem(spacerItem9)
        Form.verticalLayout_15.addWidget(Form.widget_31)
        Form.label_6 = QtGui.QLabel(Form.utilsTabPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        Form.label_6.setFont(font)
        Form.label_6.setObjectName("label_6")
        Form.verticalLayout_15.addWidget(Form.label_6)
        Form.label_7 = QtGui.QLabel(Form.utilsTabPage)
        Form.label_7.setObjectName("label_7")
        Form.verticalLayout_15.addWidget(Form.label_7)
        Form.widget_30 = QtGui.QWidget(Form.utilsTabPage)
        Form.widget_30.setObjectName("widget_30")
        Form.horizontalLayout_19 = QtGui.QHBoxLayout(Form.widget_30)
        Form.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_19.setObjectName("horizontalLayout_19")
        Form.widget_26 = QtGui.QWidget(Form.widget_30)
        Form.widget_26.setObjectName("widget_26")
        Form.gridLayout = QtGui.QGridLayout(Form.widget_26)
        Form.gridLayout.setContentsMargins(0, 0, 0, 0)
        Form.gridLayout.setObjectName("gridLayout")
        Form.installApkBtn = QtGui.QPushButton(Form.widget_26)
        Form.installApkBtn.setObjectName("installApkBtn")
        Form.gridLayout.addWidget(Form.installApkBtn, 0, 0, 1, 1)
        Form.logcatDumpBtn = QtGui.QPushButton(Form.widget_26)
        Form.logcatDumpBtn.setObjectName("logcatDumpBtn")
        Form.gridLayout.addWidget(Form.logcatDumpBtn, 0, 1, 1, 1)
        Form.flexDebugBtn = QtGui.QPushButton(Form.widget_26)
        Form.flexDebugBtn.setObjectName("flexDebugBtn")
        Form.gridLayout.addWidget(Form.flexDebugBtn, 0, 2, 1, 1)
        Form.clearLogcatBtn = QtGui.QPushButton(Form.widget_26)
        Form.clearLogcatBtn.setObjectName("clearLogcatBtn")
        Form.gridLayout.addWidget(Form.clearLogcatBtn, 1, 1, 1, 1)
        Form.horizontalLayout_19.addWidget(Form.widget_26)
        spacerItem10 = QtGui.QSpacerItem(99, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout_19.addItem(spacerItem10)
        Form.verticalLayout_15.addWidget(Form.widget_30)
        Form.label_15 = QtGui.QLabel(Form.utilsTabPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        Form.label_15.setFont(font)
        Form.label_15.setObjectName("label_15")
        Form.verticalLayout_15.addWidget(Form.label_15)
        Form.label_16 = QtGui.QLabel(Form.utilsTabPage)
        Form.label_16.setObjectName("label_16")
        Form.verticalLayout_15.addWidget(Form.label_16)
        Form.widget_29 = QtGui.QWidget(Form.utilsTabPage)
        Form.widget_29.setObjectName("widget_29")
        Form.horizontalLayout_18 = QtGui.QHBoxLayout(Form.widget_29)
        Form.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_18.setObjectName("horizontalLayout_18")
        Form.widget_27 = QtGui.QWidget(Form.widget_29)
        Form.widget_27.setObjectName("widget_27")
        Form.gridLayout_2 = QtGui.QGridLayout(Form.widget_27)
        Form.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        Form.gridLayout_2.setObjectName("gridLayout_2")
        Form.installIpaBtn = QtGui.QPushButton(Form.widget_27)
        Form.installIpaBtn.setObjectName("installIpaBtn")
        Form.gridLayout_2.addWidget(Form.installIpaBtn, 0, 0, 1, 1)
        Form.simulateBtn = QtGui.QPushButton(Form.widget_27)
        Form.simulateBtn.setObjectName("simulateBtn")
        Form.gridLayout_2.addWidget(Form.simulateBtn, 0, 1, 1, 1)
        Form.openSimDocsBtn = QtGui.QPushButton(Form.widget_27)
        Form.openSimDocsBtn.setObjectName("openSimDocsBtn")
        Form.gridLayout_2.addWidget(Form.openSimDocsBtn, 1, 1, 1, 1)
        Form.horizontalLayout_18.addWidget(Form.widget_27)
        spacerItem11 = QtGui.QSpacerItem(300, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout_18.addItem(spacerItem11)
        Form.verticalLayout_15.addWidget(Form.widget_29)
        spacerItem12 = QtGui.QSpacerItem(20, 19, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        Form.verticalLayout_15.addItem(spacerItem12)
        Form.mainTab.addTab(Form.utilsTabPage, "")
        Form.tab_2 = QtGui.QWidget()
        Form.tab_2.setObjectName("tab_2")
        Form.horizontalLayout_21 = QtGui.QHBoxLayout(Form.tab_2)
        Form.horizontalLayout_21.setObjectName("horizontalLayout_21")
        Form.widget_36 = QtGui.QWidget(Form.tab_2)
        Form.widget_36.setObjectName("widget_36")
        Form.verticalLayout_21 = QtGui.QVBoxLayout(Form.widget_36)
        Form.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_21.setObjectName("verticalLayout_21")
        Form.aneList = QtGui.QListWidget(Form.widget_36)
        Form.aneList.setObjectName("aneList")
        Form.verticalLayout_21.addWidget(Form.aneList)
        Form.horizontalLayout_21.addWidget(Form.widget_36)
        Form.widget_25 = QtGui.QWidget(Form.tab_2)
        Form.widget_25.setObjectName("widget_25")
        Form.verticalLayout_22 = QtGui.QVBoxLayout(Form.widget_25)
        Form.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_22.setObjectName("verticalLayout_22")
        Form.widget_37 = QtGui.QWidget(Form.widget_25)
        Form.widget_37.setObjectName("widget_37")
        Form.horizontalLayout_17 = QtGui.QHBoxLayout(Form.widget_37)
        Form.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_17.setObjectName("horizontalLayout_17")
        Form.aneCompileBtn = QtGui.QPushButton(Form.widget_37)
        Form.aneCompileBtn.setObjectName("aneCompileBtn")
        Form.horizontalLayout_17.addWidget(Form.aneCompileBtn)
        spacerItem13 = QtGui.QSpacerItem(42, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout_17.addItem(spacerItem13)
        Form.anePackageBtn = QtGui.QPushButton(Form.widget_37)
        Form.anePackageBtn.setObjectName("anePackageBtn")
        Form.horizontalLayout_17.addWidget(Form.anePackageBtn)
        Form.verticalLayout_22.addWidget(Form.widget_37)
        spacerItem14 = QtGui.QSpacerItem(20, 341, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        Form.verticalLayout_22.addItem(spacerItem14)
        Form.horizontalLayout_21.addWidget(Form.widget_25)
        Form.mainTab.addTab(Form.tab_2, "")
        Form.resultsTabPage = QtGui.QWidget()
        Form.resultsTabPage.setObjectName("resultsTabPage")
        Form.verticalLayout = QtGui.QVBoxLayout(Form.resultsTabPage)
        Form.verticalLayout.setObjectName("verticalLayout")
        Form.resultsTextBrowser = QtGui.QTextBrowser(Form.resultsTabPage)
        Form.resultsTextBrowser.setEnabled(True)
        Form.resultsTextBrowser.setProperty("cursor", QtCore.Qt.ArrowCursor)
        Form.resultsTextBrowser.setAcceptDrops(True)
        Form.resultsTextBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        Form.resultsTextBrowser.setObjectName("resultsTextBrowser")
        Form.verticalLayout.addWidget(Form.resultsTextBrowser)
        Form.mainTab.addTab(Form.resultsTabPage, "")
        Form.descriptorTabPage = QtGui.QWidget()
        Form.descriptorTabPage.setObjectName("descriptorTabPage")
        Form.verticalLayout_2 = QtGui.QVBoxLayout(Form.descriptorTabPage)
        Form.verticalLayout_2.setObjectName("verticalLayout_2")
        Form.label = QtGui.QLabel(Form.descriptorTabPage)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.label.setFont(font)
        Form.label.setObjectName("label")
        Form.verticalLayout_2.addWidget(Form.label)
        Form.widget_10 = QtGui.QWidget(Form.descriptorTabPage)
        Form.widget_10.setObjectName("widget_10")
        Form.horizontalLayout_6 = QtGui.QHBoxLayout(Form.widget_10)
        Form.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_6.setObjectName("horizontalLayout_6")
        Form.widget_8 = QtGui.QWidget(Form.widget_10)
        Form.widget_8.setObjectName("widget_8")
        Form.formLayout_3 = QtGui.QFormLayout(Form.widget_8)
        Form.formLayout_3.setContentsMargins(0, 0, 0, 0)
        Form.formLayout_3.setContentsMargins(0, 0, 0, 0)
        Form.formLayout_3.setObjectName("formLayout_3")
        Form.label_13 = QtGui.QLabel(Form.widget_8)
        Form.label_13.setObjectName("label_13")
        Form.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, Form.label_13)
        Form.prefixLine = QtGui.QLineEdit(Form.widget_8)
        Form.prefixLine.setObjectName("prefixLine")
        Form.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, Form.prefixLine)
        Form.label_14 = QtGui.QLabel(Form.widget_8)
        Form.label_14.setObjectName("label_14")
        Form.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, Form.label_14)
        Form.suffixSpin = QtGui.QSpinBox(Form.widget_8)
        Form.suffixSpin.setObjectName("suffixSpin")
        Form.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, Form.suffixSpin)
        Form.horizontalLayout_6.addWidget(Form.widget_8)
        spacerItem15 = QtGui.QSpacerItem(284, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout_6.addItem(spacerItem15)
        Form.verticalLayout_2.addWidget(Form.widget_10)
        Form.label_2 = QtGui.QLabel(Form.descriptorTabPage)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.label_2.setFont(font)
        Form.label_2.setObjectName("label_2")
        Form.verticalLayout_2.addWidget(Form.label_2)
        Form.widget_9 = QtGui.QWidget(Form.descriptorTabPage)
        Form.widget_9.setObjectName("widget_9")
        Form.horizontalLayout_7 = QtGui.QHBoxLayout(Form.widget_9)
        Form.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_7.setObjectName("horizontalLayout_7")
        Form.widget_3 = QtGui.QWidget(Form.widget_9)
        Form.widget_3.setObjectName("widget_3")
        Form.formLayout_2 = QtGui.QFormLayout(Form.widget_3)
        Form.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.formLayout_2.setContentsMargins(0, 0, 0, 0)
        Form.formLayout_2.setContentsMargins(0, 0, 0, 0)
        Form.formLayout_2.setObjectName("formLayout_2")
        Form.label_10 = QtGui.QLabel(Form.widget_3)
        Form.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.label_10.setObjectName("label_10")
        Form.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, Form.label_10)
        Form.majorSpin = QtGui.QSpinBox(Form.widget_3)
        Form.majorSpin.setMaximum(1000)
        Form.majorSpin.setObjectName("majorSpin")
        Form.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, Form.majorSpin)
        Form.label_11 = QtGui.QLabel(Form.widget_3)
        Form.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.label_11.setObjectName("label_11")
        Form.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, Form.label_11)
        Form.minorSpin = QtGui.QSpinBox(Form.widget_3)
        Form.minorSpin.setMaximum(10000)
        Form.minorSpin.setObjectName("minorSpin")
        Form.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, Form.minorSpin)
        Form.label_12 = QtGui.QLabel(Form.widget_3)
        Form.label_12.setObjectName("label_12")
        Form.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, Form.label_12)
        Form.revisionSpin = QtGui.QSpinBox(Form.widget_3)
        Form.revisionSpin.setMaximum(100000)
        Form.revisionSpin.setObjectName("revisionSpin")
        Form.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, Form.revisionSpin)
        Form.microSpin = QtGui.QSpinBox(Form.widget_3)
        Form.microSpin.setMaximum(100000)
        Form.microSpin.setObjectName("microSpin")
        Form.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, Form.microSpin)
        Form.label_22 = QtGui.QLabel(Form.widget_3)
        Form.label_22.setObjectName("label_22")
        Form.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, Form.label_22)
        Form.horizontalLayout_7.addWidget(Form.widget_3)
        spacerItem16 = QtGui.QSpacerItem(483, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout_7.addItem(spacerItem16)
        Form.verticalLayout_2.addWidget(Form.widget_9)
        Form.widget_11 = QtGui.QWidget(Form.descriptorTabPage)
        Form.widget_11.setObjectName("widget_11")
        Form.horizontalLayout_8 = QtGui.QHBoxLayout(Form.widget_11)
        Form.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_8.setObjectName("horizontalLayout_8")
        Form.reloadSettingsBtn = QtGui.QPushButton(Form.widget_11)
        Form.reloadSettingsBtn.setObjectName("reloadSettingsBtn")
        Form.horizontalLayout_8.addWidget(Form.reloadSettingsBtn)
        Form.incrementSettingsBtn = QtGui.QPushButton(Form.widget_11)
        Form.incrementSettingsBtn.setObjectName("incrementSettingsBtn")
        Form.horizontalLayout_8.addWidget(Form.incrementSettingsBtn)
        Form.writeSettingsBtn = QtGui.QPushButton(Form.widget_11)
        Form.writeSettingsBtn.setObjectName("writeSettingsBtn")
        Form.horizontalLayout_8.addWidget(Form.writeSettingsBtn)
        spacerItem17 = QtGui.QSpacerItem(415, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout_8.addItem(spacerItem17)
        Form.verticalLayout_2.addWidget(Form.widget_11)
        spacerItem18 = QtGui.QSpacerItem(20, 152, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        Form.verticalLayout_2.addItem(spacerItem18)
        Form.mainTab.addTab(Form.descriptorTabPage, "")
        Form.deployTabPage = QtGui.QWidget()
        Form.deployTabPage.setObjectName("deployTabPage")
        Form.verticalLayout_12 = QtGui.QVBoxLayout(Form.deployTabPage)
        Form.verticalLayout_12.setObjectName("verticalLayout_12")
        Form.line = QtGui.QFrame(Form.deployTabPage)
        Form.line.setFrameShape(QtGui.QFrame.HLine)
        Form.line.setFrameShadow(QtGui.QFrame.Sunken)
        Form.line.setObjectName("line")
        Form.verticalLayout_12.addWidget(Form.line)
        Form.widget_18 = QtGui.QWidget(Form.deployTabPage)
        Form.widget_18.setObjectName("widget_18")
        Form.horizontalLayout_11 = QtGui.QHBoxLayout(Form.widget_18)
        Form.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_11.setObjectName("horizontalLayout_11")
        Form.widget_13 = QtGui.QWidget(Form.widget_18)
        Form.widget_13.setObjectName("widget_13")
        Form.verticalLayout_3 = QtGui.QVBoxLayout(Form.widget_13)
        Form.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_3.setObjectName("verticalLayout_3")
        Form.widget_20 = QtGui.QWidget(Form.widget_13)
        Form.widget_20.setObjectName("widget_20")
        Form.horizontalLayout_12 = QtGui.QHBoxLayout(Form.widget_20)
        Form.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_12.setObjectName("horizontalLayout_12")
        Form.label_17 = QtGui.QLabel(Form.widget_20)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        Form.label_17.setFont(font)
        Form.label_17.setObjectName("label_17")
        Form.horizontalLayout_12.addWidget(Form.label_17)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout_12.addItem(spacerItem19)
        Form.summaryDefaultBtn = QtGui.QPushButton(Form.widget_20)
        font = QtGui.QFont()
        font.setPointSize(8)
        Form.summaryDefaultBtn.setFont(font)
        Form.summaryDefaultBtn.setObjectName("summaryDefaultBtn")
        Form.horizontalLayout_12.addWidget(Form.summaryDefaultBtn)
        Form.verticalLayout_3.addWidget(Form.widget_20)
        Form.summaryText = QtGui.QPlainTextEdit(Form.widget_13)
        Form.summaryText.setObjectName("summaryText")
        Form.verticalLayout_3.addWidget(Form.summaryText)
        Form.horizontalLayout_11.addWidget(Form.widget_13)
        Form.widget_16 = QtGui.QWidget(Form.widget_18)
        Form.widget_16.setObjectName("widget_16")
        Form.verticalLayout_11 = QtGui.QVBoxLayout(Form.widget_16)
        Form.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_11.setObjectName("verticalLayout_11")
        Form.widget_21 = QtGui.QWidget(Form.widget_16)
        Form.widget_21.setObjectName("widget_21")
        Form.horizontalLayout_13 = QtGui.QHBoxLayout(Form.widget_21)
        Form.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_13.setObjectName("horizontalLayout_13")
        Form.label_19 = QtGui.QLabel(Form.widget_21)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        Form.label_19.setFont(font)
        Form.label_19.setObjectName("label_19")
        Form.horizontalLayout_13.addWidget(Form.label_19)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout_13.addItem(spacerItem20)
        Form.additionsDefaultBtn = QtGui.QPushButton(Form.widget_21)
        font = QtGui.QFont()
        font.setPointSize(8)
        Form.additionsDefaultBtn.setFont(font)
        Form.additionsDefaultBtn.setObjectName("additionsDefaultBtn")
        Form.horizontalLayout_13.addWidget(Form.additionsDefaultBtn)
        Form.verticalLayout_11.addWidget(Form.widget_21)
        Form.additionsText = QtGui.QPlainTextEdit(Form.widget_16)
        Form.additionsText.setObjectName("additionsText")
        Form.verticalLayout_11.addWidget(Form.additionsText)
        Form.horizontalLayout_11.addWidget(Form.widget_16)
        Form.verticalLayout_12.addWidget(Form.widget_18)
        Form.widget_19 = QtGui.QWidget(Form.deployTabPage)
        Form.widget_19.setObjectName("widget_19")
        Form.horizontalLayout_10 = QtGui.QHBoxLayout(Form.widget_19)
        Form.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_10.setObjectName("horizontalLayout_10")
        Form.widget_14 = QtGui.QWidget(Form.widget_19)
        Form.widget_14.setObjectName("widget_14")
        Form.verticalLayout_9 = QtGui.QVBoxLayout(Form.widget_14)
        Form.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_9.setObjectName("verticalLayout_9")
        Form.widget_22 = QtGui.QWidget(Form.widget_14)
        Form.widget_22.setObjectName("widget_22")
        Form.horizontalLayout_14 = QtGui.QHBoxLayout(Form.widget_22)
        Form.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_14.setObjectName("horizontalLayout_14")
        Form.label_18 = QtGui.QLabel(Form.widget_22)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        Form.label_18.setFont(font)
        Form.label_18.setObjectName("label_18")
        Form.horizontalLayout_14.addWidget(Form.label_18)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout_14.addItem(spacerItem21)
        Form.fixesDefaultBtn = QtGui.QPushButton(Form.widget_22)
        font = QtGui.QFont()
        font.setPointSize(8)
        Form.fixesDefaultBtn.setFont(font)
        Form.fixesDefaultBtn.setObjectName("fixesDefaultBtn")
        Form.horizontalLayout_14.addWidget(Form.fixesDefaultBtn)
        Form.verticalLayout_9.addWidget(Form.widget_22)
        Form.fixesText = QtGui.QPlainTextEdit(Form.widget_14)
        Form.fixesText.setObjectName("fixesText")
        Form.verticalLayout_9.addWidget(Form.fixesText)
        Form.horizontalLayout_10.addWidget(Form.widget_14)
        Form.widget_15 = QtGui.QWidget(Form.widget_19)
        Form.widget_15.setObjectName("widget_15")
        Form.verticalLayout_10 = QtGui.QVBoxLayout(Form.widget_15)
        Form.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_10.setObjectName("verticalLayout_10")
        Form.widget_23 = QtGui.QWidget(Form.widget_15)
        Form.widget_23.setObjectName("widget_23")
        Form.horizontalLayout_15 = QtGui.QHBoxLayout(Form.widget_23)
        Form.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_15.setObjectName("horizontalLayout_15")
        Form.label_20 = QtGui.QLabel(Form.widget_23)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        Form.label_20.setFont(font)
        Form.label_20.setObjectName("label_20")
        Form.horizontalLayout_15.addWidget(Form.label_20)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout_15.addItem(spacerItem22)
        Form.removalsDefaultBtn = QtGui.QPushButton(Form.widget_23)
        font = QtGui.QFont()
        font.setPointSize(8)
        Form.removalsDefaultBtn.setFont(font)
        Form.removalsDefaultBtn.setObjectName("removalsDefaultBtn")
        Form.horizontalLayout_15.addWidget(Form.removalsDefaultBtn)
        Form.verticalLayout_10.addWidget(Form.widget_23)
        Form.removalsText = QtGui.QPlainTextEdit(Form.widget_15)
        Form.removalsText.setObjectName("removalsText")
        Form.verticalLayout_10.addWidget(Form.removalsText)
        Form.horizontalLayout_10.addWidget(Form.widget_15)
        Form.verticalLayout_12.addWidget(Form.widget_19)
        Form.widget_17 = QtGui.QWidget(Form.deployTabPage)
        Form.widget_17.setObjectName("widget_17")
        Form.verticalLayout_8 = QtGui.QVBoxLayout(Form.widget_17)
        Form.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_8.setObjectName("verticalLayout_8")
        Form.widget_24 = QtGui.QWidget(Form.widget_17)
        Form.widget_24.setObjectName("widget_24")
        Form.horizontalLayout_16 = QtGui.QHBoxLayout(Form.widget_24)
        Form.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_16.setObjectName("horizontalLayout_16")
        Form.label_21 = QtGui.QLabel(Form.widget_24)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        Form.label_21.setFont(font)
        Form.label_21.setObjectName("label_21")
        Form.horizontalLayout_16.addWidget(Form.label_21)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout_16.addItem(spacerItem23)
        Form.releaseInfoDefaultBtn = QtGui.QPushButton(Form.widget_24)
        font = QtGui.QFont()
        font.setPointSize(8)
        Form.releaseInfoDefaultBtn.setFont(font)
        Form.releaseInfoDefaultBtn.setObjectName("releaseInfoDefaultBtn")
        Form.horizontalLayout_16.addWidget(Form.releaseInfoDefaultBtn)
        Form.verticalLayout_8.addWidget(Form.widget_24)
        Form.releaseInfoText = QtGui.QPlainTextEdit(Form.widget_17)
        Form.releaseInfoText.setObjectName("releaseInfoText")
        Form.verticalLayout_8.addWidget(Form.releaseInfoText)
        Form.verticalLayout_12.addWidget(Form.widget_17)
        Form.widget_12 = QtGui.QWidget(Form.deployTabPage)
        Form.widget_12.setObjectName("widget_12")
        Form.horizontalLayout_9 = QtGui.QHBoxLayout(Form.widget_12)
        Form.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_9.setObjectName("horizontalLayout_9")
        Form.deployBuildBtn = QtGui.QPushButton(Form.widget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.deployBuildBtn.setFont(font)
        Form.deployBuildBtn.setObjectName("deployBuildBtn")
        Form.horizontalLayout_9.addWidget(Form.deployBuildBtn)
        spacerItem24 = QtGui.QSpacerItem(514, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout_9.addItem(spacerItem24)
        Form.resetDeployBtn = QtGui.QPushButton(Form.widget_12)
        Form.resetDeployBtn.setObjectName("resetDeployBtn")
        Form.horizontalLayout_9.addWidget(Form.resetDeployBtn)
        Form.reloadDeployBtn = QtGui.QPushButton(Form.widget_12)
        Form.reloadDeployBtn.setObjectName("reloadDeployBtn")
        Form.horizontalLayout_9.addWidget(Form.reloadDeployBtn)
        Form.saveDeployBtn = QtGui.QPushButton(Form.widget_12)
        Form.saveDeployBtn.setObjectName("saveDeployBtn")
        Form.horizontalLayout_9.addWidget(Form.saveDeployBtn)
        Form.verticalLayout_12.addWidget(Form.widget_12)
        Form.mainTab.addTab(Form.deployTabPage, "")
        Form.tab = QtGui.QWidget()
        Form.tab.setObjectName("tab")
        Form.verticalLayout_14 = QtGui.QVBoxLayout(Form.tab)
        Form.verticalLayout_14.setObjectName("verticalLayout_14")
        Form.textEdit = QtGui.QTextEdit(Form.tab)
        Form.textEdit.setObjectName("textEdit")
        Form.verticalLayout_14.addWidget(Form.textEdit)
        Form.mainTab.addTab(Form.tab, "")
        Form.horizontalLayout_5.addWidget(Form.mainTab)

        self.retranslateUi(Form)
        Form.mainTab.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(Form.summaryText, Form.additionsText)
        Form.setTabOrder(Form.additionsText, Form.fixesText)
        Form.setTabOrder(Form.fixesText, Form.removalsText)
        Form.setTabOrder(Form.removalsText, Form.releaseInfoText)
        Form.setTabOrder(Form.releaseInfoText, Form.deployBuildBtn)
        Form.setTabOrder(Form.deployBuildBtn, Form.flashPlayerComboBox)
        Form.setTabOrder(Form.flashPlayerComboBox, Form.airSDKComboBox)
        Form.setTabOrder(Form.airSDKComboBox, Form.prefixLine)
        Form.setTabOrder(Form.prefixLine, Form.suffixSpin)
        Form.setTabOrder(Form.suffixSpin, Form.majorSpin)
        Form.setTabOrder(Form.majorSpin, Form.minorSpin)
        Form.setTabOrder(Form.minorSpin, Form.revisionSpin)
        Form.setTabOrder(Form.revisionSpin, Form.reloadSettingsBtn)
        Form.setTabOrder(Form.reloadSettingsBtn, Form.incrementSettingsBtn)
        Form.setTabOrder(Form.incrementSettingsBtn, Form.writeSettingsBtn)
        Form.setTabOrder(Form.writeSettingsBtn, Form.installApkBtn)
        Form.setTabOrder(Form.installApkBtn, Form.runDebugBtn)
        Form.setTabOrder(Form.runDebugBtn, Form.logcatDumpBtn)
        Form.setTabOrder(Form.logcatDumpBtn, Form.clearLogcatBtn)
        Form.setTabOrder(Form.clearLogcatBtn, Form.flexDebugBtn)
        Form.setTabOrder(Form.flexDebugBtn, Form.installIpaBtn)
        Form.setTabOrder(Form.installIpaBtn, Form.resultsTextBrowser)
        Form.setTabOrder(Form.resultsTextBrowser, Form.remoteDebugComboBox)
        Form.setTabOrder(Form.remoteDebugComboBox, Form.webPlatformCheck)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "ANE Compiler", None, QtGui.QApplication.UnicodeUTF8))
        Form.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Compile Modes", None, QtGui.QApplication.UnicodeUTF8))
        Form.liveCheck.setText(QtGui.QApplication.translate("Form", "Live (Server)", None, QtGui.QApplication.UnicodeUTF8))
        Form.telemetryCheck.setText(QtGui.QApplication.translate("Form", "Adv. Telemetry", None, QtGui.QApplication.UnicodeUTF8))
        Form.platformBox.setTitle(QtGui.QApplication.translate("Form", "Web", None, QtGui.QApplication.UnicodeUTF8))
        Form.webPlatformCheck.setText(QtGui.QApplication.translate("Form", "Web (Flash)", None, QtGui.QApplication.UnicodeUTF8))
        Form.groupBox.setTitle(QtGui.QApplication.translate("Form", "Mobile", None, QtGui.QApplication.UnicodeUTF8))
        Form.iosPlatformCheck.setText(QtGui.QApplication.translate("Form", "iOS", None, QtGui.QApplication.UnicodeUTF8))
        Form.iosInterpCheck.setText(QtGui.QApplication.translate("Form", "Interpreter", None, QtGui.QApplication.UnicodeUTF8))
        Form.simulatorCheck.setText(QtGui.QApplication.translate("Form", "Simulator", None, QtGui.QApplication.UnicodeUTF8))
        Form.androidPlatformCheck.setText(QtGui.QApplication.translate("Form", "Android", None, QtGui.QApplication.UnicodeUTF8))
        Form.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Desktop", None, QtGui.QApplication.UnicodeUTF8))
        Form.airPlatformCheck.setText(QtGui.QApplication.translate("Form", "AIR", None, QtGui.QApplication.UnicodeUTF8))
        Form.nativePlatformCheck.setText(QtGui.QApplication.translate("Form", "Native", None, QtGui.QApplication.UnicodeUTF8))
        Form.nativeCaptiveChk.setText(QtGui.QApplication.translate("Form", "Captive", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_3.setText(QtGui.QApplication.translate("Form", "Flash Player Version:", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_4.setText(QtGui.QApplication.translate("Form", "AIR SDK Version:", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_5.setText(QtGui.QApplication.translate("Form", "Remote Debugging:", None, QtGui.QApplication.UnicodeUTF8))
        Form.compileBtn.setText(QtGui.QApplication.translate("Form", "Compile", None, QtGui.QApplication.UnicodeUTF8))
        Form.compileDebugBtn.setText(QtGui.QApplication.translate("Form", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        Form.compileBeforePackageChk.setText(QtGui.QApplication.translate("Form", "Compile Before Packaging", None, QtGui.QApplication.UnicodeUTF8))
        Form.packagePauseChk.setText(QtGui.QApplication.translate("Form", "Notify Each Step (Pause)", None, QtGui.QApplication.UnicodeUTF8))
        Form.expandPackageChk.setText(QtGui.QApplication.translate("Form", "Append to Previous Package", None, QtGui.QApplication.UnicodeUTF8))
        Form.packageBtn.setText(QtGui.QApplication.translate("Form", "Package", None, QtGui.QApplication.UnicodeUTF8))
        Form.mainTab.setTabText(Form.mainTab.indexOf(Form.settingsTabPage), QtGui.QApplication.translate("Form", "Compile", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_8.setText(QtGui.QApplication.translate("Form", "Desktop", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_9.setText(QtGui.QApplication.translate("Form", "Desktop Device Utilities", None, QtGui.QApplication.UnicodeUTF8))
        Form.runDebugBtn.setText(QtGui.QApplication.translate("Form", "Run Debug", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_6.setText(QtGui.QApplication.translate("Form", "Android", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_7.setText(QtGui.QApplication.translate("Form", "Android Device Utilities", None, QtGui.QApplication.UnicodeUTF8))
        Form.installApkBtn.setText(QtGui.QApplication.translate("Form", "Install APK", None, QtGui.QApplication.UnicodeUTF8))
        Form.logcatDumpBtn.setText(QtGui.QApplication.translate("Form", "Echo Logcat Dump", None, QtGui.QApplication.UnicodeUTF8))
        Form.flexDebugBtn.setText(QtGui.QApplication.translate("Form", "FDB Debug Session", None, QtGui.QApplication.UnicodeUTF8))
        Form.clearLogcatBtn.setText(QtGui.QApplication.translate("Form", "Clear Logcat", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_15.setText(QtGui.QApplication.translate("Form", "iOS", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_16.setText(QtGui.QApplication.translate("Form", "iOS Device Utilities", None, QtGui.QApplication.UnicodeUTF8))
        Form.installIpaBtn.setText(QtGui.QApplication.translate("Form", "Install IPA", None, QtGui.QApplication.UnicodeUTF8))
        Form.simulateBtn.setText(QtGui.QApplication.translate("Form", "Simulate App", None, QtGui.QApplication.UnicodeUTF8))
        Form.openSimDocsBtn.setText(QtGui.QApplication.translate("Form", "Finder Documents", None, QtGui.QApplication.UnicodeUTF8))
        Form.mainTab.setTabText(Form.mainTab.indexOf(Form.utilsTabPage), QtGui.QApplication.translate("Form", "Utilities", None, QtGui.QApplication.UnicodeUTF8))
        Form.aneCompileBtn.setText(QtGui.QApplication.translate("Form", "Compile", None, QtGui.QApplication.UnicodeUTF8))
        Form.anePackageBtn.setText(QtGui.QApplication.translate("Form", "Package", None, QtGui.QApplication.UnicodeUTF8))
        Form.mainTab.setTabText(Form.mainTab.indexOf(Form.tab_2), QtGui.QApplication.translate("Form", "Extensions", None, QtGui.QApplication.UnicodeUTF8))
        Form.mainTab.setTabText(Form.mainTab.indexOf(Form.resultsTabPage), QtGui.QApplication.translate("Form", "Results", None, QtGui.QApplication.UnicodeUTF8))
        Form.label.setText(QtGui.QApplication.translate("Form", "Version Label:", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_13.setText(QtGui.QApplication.translate("Form", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_14.setText(QtGui.QApplication.translate("Form", "Suffix", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_2.setText(QtGui.QApplication.translate("Form", "Version Number:", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_10.setText(QtGui.QApplication.translate("Form", "Major", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_11.setText(QtGui.QApplication.translate("Form", "Minor", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_12.setText(QtGui.QApplication.translate("Form", "Revision", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_22.setText(QtGui.QApplication.translate("Form", "Micro", None, QtGui.QApplication.UnicodeUTF8))
        Form.reloadSettingsBtn.setText(QtGui.QApplication.translate("Form", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        Form.incrementSettingsBtn.setText(QtGui.QApplication.translate("Form", "Increment", None, QtGui.QApplication.UnicodeUTF8))
        Form.writeSettingsBtn.setText(QtGui.QApplication.translate("Form", "Write", None, QtGui.QApplication.UnicodeUTF8))
        Form.mainTab.setTabText(Form.mainTab.indexOf(Form.descriptorTabPage), QtGui.QApplication.translate("Form", "Version", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_17.setText(QtGui.QApplication.translate("Form", "Summary", None, QtGui.QApplication.UnicodeUTF8))
        Form.summaryDefaultBtn.setText(QtGui.QApplication.translate("Form", "Set As Default", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_19.setText(QtGui.QApplication.translate("Form", "New Additions", None, QtGui.QApplication.UnicodeUTF8))
        Form.additionsDefaultBtn.setText(QtGui.QApplication.translate("Form", "Set As Default", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_18.setText(QtGui.QApplication.translate("Form", "Fixes & Changes", None, QtGui.QApplication.UnicodeUTF8))
        Form.fixesDefaultBtn.setText(QtGui.QApplication.translate("Form", "Set As Default", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_20.setText(QtGui.QApplication.translate("Form", "Removals", None, QtGui.QApplication.UnicodeUTF8))
        Form.removalsDefaultBtn.setText(QtGui.QApplication.translate("Form", "Set As Default", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_21.setText(QtGui.QApplication.translate("Form", "Release Information", None, QtGui.QApplication.UnicodeUTF8))
        Form.releaseInfoDefaultBtn.setText(QtGui.QApplication.translate("Form", "Set As Default", None, QtGui.QApplication.UnicodeUTF8))
        Form.deployBuildBtn.setText(QtGui.QApplication.translate("Form", "Deploy", None, QtGui.QApplication.UnicodeUTF8))
        Form.resetDeployBtn.setText(QtGui.QApplication.translate("Form", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        Form.reloadDeployBtn.setText(QtGui.QApplication.translate("Form", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        Form.saveDeployBtn.setText(QtGui.QApplication.translate("Form", "Save", None, QtGui.QApplication.UnicodeUTF8))
        Form.mainTab.setTabText(Form.mainTab.indexOf(Form.deployTabPage), QtGui.QApplication.translate("Form", "Deploy", None, QtGui.QApplication.UnicodeUTF8))
        Form.textEdit.setHtml(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.Lucida Grande UI\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; color:#000000;\">1) You first need to start the application on the iOS device</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></span><a href=\"http://help.adobe.com/en_US/air/build/WS901d38e593cd1bac7b2281cc12cd6bced97-8000.html\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; text-decoration: underline; color:#000000;\">2) Get the decide Handle from idb.exe:</span></a></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\'; font-size:10pt; color:#5555ff;\">AIR/3.8/lib/aot/bin/iOSBin/idb</span><span style=\" font-family:\'Courier New,courier\'; font-size:10pt; color:#5555ff;\">/idb -devices </span><span style=\" font-family:\'Courier New,courier\'; font-size:10pt; color:#005500;\">(probably going to be 1)</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://help.adobe.com/en_US/air/build/WS901d38e593cd1bac7b2281cc12cd6bced97-8000.html\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; text-decoration: underline; color:#000000;\">3) Forward desktop debugging port to remote iOS debugging port:</span></a></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New,courier\'; font-size:10pt; color:#333333;\">idb -forward 7936 16000 1</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://help.adobe.com/en_US/air/build/WS901d38e593cd1bac7b2281cc12cd6bced97-8000.html\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; text-decoration: underline; color:#000000;\">4) Run FDB using the desktop port:</span></a></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">fdb -p 7936</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://help.adobe.com/en_US/air/build/WS901d38e593cd1bac7b2281cc12cd6bced97-8000.html\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; text-decoration: underline; color:#000000;\">5) Inside FDB run the debugging instance:</span></a></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://help.adobe.com/en_US/air/build/WS901d38e593cd1bac7b2281cc12cd6bced97-8000.html\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; text-decoration: underline; color:#000000;\">(fdb) run</span></a></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://help.adobe.com/en_US/air/build/WS901d38e593cd1bac7b2281cc12cd6bced97-8000.html\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; text-decoration: underline; color:#000000;\">For details see:</span></a></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://help.adobe.com/en_US/air/build/WS901d38e593cd1bac7b2281cc12cd6bced97-8000.html\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; text-decoration: underline; color:#0000ff;\">http://help.adobe.com/en_US/air/build/WS901d38e593cd1bac7b2281cc12cd6bced97-8000.html</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        Form.mainTab.setTabText(Form.mainTab.indexOf(Form.tab), QtGui.QApplication.translate("Form", "Debug Info", None, QtGui.QApplication.UnicodeUTF8))

